package com.possible_triangle.dye_the_world.index

import com.possible_triangle.dye_the_world.Constants.Mods.ARTS_AND_CRAFTS
import com.possible_triangle.dye_the_world.ForgeEntrypoint.REGISTRATE
import com.possible_triangle.dye_the_world.compat.artsandcrafts.DyedFlowerPotBlock
import com.possible_triangle.dye_the_world.data.*
import com.possible_triangle.dye_the_world.dyesFor
import com.possible_triangle.dye_the_world.extensions.*
import com.possible_triangle.dye_the_world.extensions.createId
import com.possible_triangle.dye_the_world.translation
import net.minecraft.core.registries.BuiltInRegistries
import net.minecraft.core.registries.Registries
import net.minecraft.data.recipes.RecipeCategory.BUILDING_BLOCKS
import net.minecraft.resources.ResourceLocation
import net.minecraft.tags.BlockTags
import net.minecraft.tags.ItemTags
import net.minecraft.tags.TagKey
import net.minecraft.world.item.CreativeModeTabs
import net.minecraft.world.item.DyeColor
import net.minecraft.world.item.Item
import net.minecraft.world.level.block.Block
import net.minecraft.world.level.block.SlabBlock
import net.minecraft.world.level.block.StairBlock
import net.minecraft.world.level.block.WallBlock
import net.minecraft.world.level.block.state.BlockBehaviour
import java.lang.reflect.Constructor

/**
 * Registers Arts and Crafts-style blocks for Dye Depot colors (amber, aqua, verdant, etc.)
 * in the dye_the_world namespace. Blockstates and models are generated by ArtsAndCraftsAssetProvider.
 */
object DyedArtsAndCrafts {
    private val DYES = dyesFor(ARTS_AND_CRAFTS)
    private val CHALK_STICKS_TAG: TagKey<Item> = TagKey.create(Registries.ITEM, ARTS_AND_CRAFTS.createId("chalk_sticks"))
    private val PAINTBRUSHES_TAG: TagKey<Item> = TagKey.create(Registries.ITEM, ARTS_AND_CRAFTS.createId("paintbrushes"))
    private val POTTED_VARIANTS =
        listOf(
            PottedVariant("potted_acacia_sapling", "minecraft:acacia_sapling"),
            PottedVariant("potted_allium", "minecraft:allium"),
            PottedVariant("potted_azure_bluet", "minecraft:azure_bluet"),
            PottedVariant("potted_bamboo", "minecraft:bamboo"),
            PottedVariant("potted_birch_sapling", "minecraft:birch_sapling"),
            PottedVariant("potted_blue_orchid", "minecraft:blue_orchid"),
            PottedVariant("potted_brown_mushroom", "minecraft:brown_mushroom"),
            PottedVariant("potted_cactus", "minecraft:cactus"),
            PottedVariant("potted_cherry_sapling", "minecraft:cherry_sapling"),
            PottedVariant("potted_cork_sapling", "arts_and_crafts:cork_sapling"),
            PottedVariant("potted_cornflower", "minecraft:cornflower"),
            PottedVariant("potted_crimson_fungus", "minecraft:crimson_fungus"),
            PottedVariant("potted_crimson_roots", "minecraft:crimson_roots"),
            PottedVariant("potted_dandelion", "minecraft:dandelion"),
            PottedVariant("potted_dark_oak_sapling", "minecraft:dark_oak_sapling"),
            PottedVariant("potted_dead_bush", "minecraft:dead_bush"),
            PottedVariant("potted_fern", "minecraft:fern"),
            PottedVariant("potted_jungle_sapling", "minecraft:jungle_sapling"),
            PottedVariant("potted_lily_of_the_valley", "minecraft:lily_of_the_valley"),
            PottedVariant("potted_mangrove_propagule", "minecraft:mangrove_propagule"),
            PottedVariant("potted_oak_sapling", "minecraft:oak_sapling"),
            PottedVariant("potted_orange_tulip", "minecraft:orange_tulip"),
            PottedVariant("potted_oxeye_daisy", "minecraft:oxeye_daisy"),
            PottedVariant("potted_pink_tulip", "minecraft:pink_tulip"),
            PottedVariant("potted_poppy", "minecraft:poppy"),
            PottedVariant("potted_azalea_bush", "minecraft:azalea"),
            PottedVariant("potted_flowering_azalea_bush", "minecraft:flowering_azalea"),
            PottedVariant("potted_red_mushroom", "minecraft:red_mushroom"),
            PottedVariant("potted_red_tulip", "minecraft:red_tulip"),
            PottedVariant("potted_spruce_sapling", "minecraft:spruce_sapling"),
            PottedVariant("potted_torchflower", "minecraft:torchflower"),
            PottedVariant("potted_warped_fungus", "minecraft:warped_fungus"),
            PottedVariant("potted_warped_roots", "minecraft:warped_roots"),
            PottedVariant("potted_white_tulip", "minecraft:white_tulip"),
            PottedVariant("potted_wither_rose", "minecraft:wither_rose"),
        )

    private data class PottedVariant(
        val suffix: String,
        val plantId: String,
    )

    private val CHALK_STICK_CTOR: Constructor<*> by lazy {
        Class
            .forName("com.kekecreations.arts_and_crafts.common.item.ChalkStickItem")
            .getConstructor(Integer::class.java, Item.Properties::class.java)
    }
    private val CHALK_DUST_BLOCK_CTOR: Constructor<*> by lazy {
        Class
            .forName("com.kekecreations.arts_and_crafts.common.block.ChalkDustBlock")
            .getConstructor(Integer::class.java, BlockBehaviour.Properties::class.java)
    }
    private val PAINTBRUSH_CTOR: Constructor<*> by lazy {
        Class
            .forName("com.kekecreations.arts_and_crafts.common.item.PaintbrushItem")
            .getConstructor(Item.Properties::class.java)
    }
    private val PLASTER_BLOCK_CTOR: Constructor<*> by lazy {
        Class
            .forName("com.kekecreations.arts_and_crafts.common.block.PlasterBlock")
            .getConstructor(DyeColor::class.java, BlockBehaviour.Properties::class.java)
    }

    private fun createArtsAndCraftsChalkStick(
        dyeId: Int,
        properties: Item.Properties,
    ): Item {
        try {
            return CHALK_STICK_CTOR.newInstance(dyeId, properties) as Item
        } catch (exception: ReflectiveOperationException) {
            throw IllegalStateException("Failed to create Arts and Crafts chalk stick for dye id=$dyeId", exception)
        }
    }

    private fun createArtsAndCraftsChalkDust(
        dyeId: Int,
        properties: BlockBehaviour.Properties,
    ): Block {
        try {
            return CHALK_DUST_BLOCK_CTOR.newInstance(dyeId, properties) as Block
        } catch (exception: ReflectiveOperationException) {
            throw IllegalStateException("Failed to create Arts and Crafts chalk dust for dye id=$dyeId", exception)
        }
    }

    private fun createArtsAndCraftsPaintbrush(properties: Item.Properties): Item {
        try {
            return PAINTBRUSH_CTOR.newInstance(properties) as Item
        } catch (exception: ReflectiveOperationException) {
            throw IllegalStateException("Failed to create Arts and Crafts paintbrush", exception)
        }
    }

    private fun createArtsAndCraftsPlaster(properties: BlockBehaviour.Properties): Block {
        try {
            // Custom Dye Depot colors do not map to vanilla DyeColor; A&C base plaster uses null too.
            return PLASTER_BLOCK_CTOR.newInstance(null, properties) as Block
        } catch (exception: ReflectiveOperationException) {
            throw IllegalStateException("Failed to create Arts and Crafts plaster block", exception)
        }
    }

    private fun registerChalkBlocks() {
        DYES.associateWith { dye ->
            REGISTRATE
                .`object`("${dye}_chalk")
                .dyedBlock(dye, ARTS_AND_CRAFTS, ::Block)
                .initialProperties { BuiltInRegistries.BLOCK.get(ARTS_AND_CRAFTS.createId("cyan_chalk")) }
                .optionalTag(BlockTags.MINEABLE_WITH_PICKAXE)
                .blockstate { _, _ -> }
                .lang("${dye.translation} Chalk")
                .withItem {
                    tab(CreativeModeTabs.COLORED_BLOCKS)
                    tab(CreativeModeTabs.BUILDING_BLOCKS)
                    model { context, provider ->
                        provider.withExistingParent(context.name, ARTS_AND_CRAFTS.createId("block/${dye}_chalk"))
                    }
                }.register()
        }
    }

    private fun registerChalkDust() {
        DYES.associateWith { dye ->
            REGISTRATE
                .`object`("${dye}_chalk_dust")
                .dyedBlock(dye, ARTS_AND_CRAFTS) { props -> createArtsAndCraftsChalkDust(dye.id, props) }
                .initialProperties { BuiltInRegistries.BLOCK.get(ARTS_AND_CRAFTS.createId("cyan_chalk_dust")) }
                .blockstate { _, _ -> }
                .lang("${dye.translation} Chalk Dust")
                .register()
        }
    }

    private fun registerChalkSticks() {
        DYES.associateWith { dye ->
            REGISTRATE
                .`object`("${dye}_chalk_stick")
                .dyedItem(dye, ARTS_AND_CRAFTS) { props ->
                    createArtsAndCraftsChalkStick(dye.id, props.stacksTo(1).durability(32))
                }.optionalTag(CHALK_STICKS_TAG)
                .lang("${dye.translation} Chalk Stick")
                .tab(CreativeModeTabs.TOOLS_AND_UTILITIES)
                .model { context, provider ->
                    provider
                        .withExistingParent(context.name, "minecraft:item/handheld")
                        .texture("layer0", ARTS_AND_CRAFTS.createId("item/${dye}_chalk_stick"))
                }.register()
        }
    }

    private fun registerPaintbrushes() {
        DYES.associateWith { dye ->
            REGISTRATE
                .`object`("${dye}_paintbrush")
                .dyedItem(dye, ARTS_AND_CRAFTS) { props ->
                    createArtsAndCraftsPaintbrush(props.stacksTo(1).durability(48))
                }.optionalTag(PAINTBRUSHES_TAG)
                .lang("${dye.translation} Paintbrush")
                .tab(CreativeModeTabs.TOOLS_AND_UTILITIES)
                .model { context, provider ->
                    provider
                        .withExistingParent(context.name, "minecraft:item/handheld")
                        .texture("layer0", ARTS_AND_CRAFTS.createId("item/${dye}_paintbrush"))
                }.register()
        }
    }

    private fun registerBlockType(
        baseName: String,
        cubeName: String,
        cyanBlockPath: String,
        hasStairs: Boolean = true,
        hasSlab: Boolean = true,
        hasWall: Boolean = true,
    ) {
        val fullBlocks =
            DYES.associateWith { dye ->
                REGISTRATE
                    .`object`("${dye}_$cubeName")
                    .dyedBlock(dye, ARTS_AND_CRAFTS, ::Block)
                    .initialProperties { BuiltInRegistries.BLOCK.get(ARTS_AND_CRAFTS.createId(cyanBlockPath)) }
                    .optionalTag(BlockTags.MINEABLE_WITH_PICKAXE)
                    .blockstate { _, _ -> }
                    .lang("${dye.translation} ${cubeName.split("_").joinToString(" ") { it.replaceFirstChar { c -> c.uppercase() } }}")
                    .withItem {
                        tab(CreativeModeTabs.COLORED_BLOCKS)
                        tab(CreativeModeTabs.BUILDING_BLOCKS)
                    }.register()
            }

        if (hasSlab) {
            DYES.associateWith { dye ->
                REGISTRATE
                    .`object`("${dye}_${baseName}_slab")
                    .dyedBlock(dye, ARTS_AND_CRAFTS, ::SlabBlock)
                    .initialProperties { fullBlocks[dye]!!.get() }
                    .optionalTag(BlockTags.MINEABLE_WITH_PICKAXE)
                    .optionalTag(BlockTags.SLABS)
                    .blockstate { _, _ -> }
                    .lang("${dye.translation} ${baseName.split("_").joinToString(" ") { it.replaceFirstChar { c -> c.uppercase() } }} Slab")
                    .loot { c, p -> c.add(p, c.createSlabItemTable(p)) }
                    .withItem {
                        tab(CreativeModeTabs.COLORED_BLOCKS)
                        tab(CreativeModeTabs.BUILDING_BLOCKS)
                        optionalTag(ItemTags.SLABS)
                        recipe {
                            context,
                            provider,
                            ->
                            provider.slab(fullBlocks[dye]!!.asIngredient(), BUILDING_BLOCKS, context, null, true)
                        }
                    }.register()
            }
        }
        if (hasStairs) {
            DYES.associateWith { dye ->
                REGISTRATE
                    .`object`("${dye}_${baseName}_stairs")
                    .dyedBlock(dye, ARTS_AND_CRAFTS) { props -> StairBlock(fullBlocks[dye]!!.get().defaultBlockState(), props) }
                    .initialProperties { fullBlocks[dye]!!.get() }
                    .optionalTag(BlockTags.MINEABLE_WITH_PICKAXE)
                    .optionalTag(BlockTags.STAIRS)
                    .blockstate { _, _ -> }
                    .lang(
                        "${dye.translation} ${baseName.split("_").joinToString(" ") {
                            it.replaceFirstChar { c ->
                                c.uppercase()
                            }
                        }} Stairs",
                    ).withItem {
                        tab(CreativeModeTabs.COLORED_BLOCKS)
                        tab(CreativeModeTabs.BUILDING_BLOCKS)
                        optionalTag(ItemTags.STAIRS)
                        recipe {
                            context,
                            provider,
                            ->
                            provider.stairs(fullBlocks[dye]!!.asIngredient(), BUILDING_BLOCKS, context, null, true)
                        }
                    }.register()
            }
        }
        if (hasWall) {
            DYES.associateWith { dye ->
                REGISTRATE
                    .`object`("${dye}_${baseName}_wall")
                    .dyedBlock(dye, ARTS_AND_CRAFTS, ::WallBlock)
                    .initialProperties { fullBlocks[dye]!!.get() }
                    .optionalTag(BlockTags.MINEABLE_WITH_PICKAXE)
                    .optionalTag(BlockTags.WALLS)
                    .blockstate { _, _ -> }
                    .lang("${dye.translation} ${baseName.split("_").joinToString(" ") { it.replaceFirstChar { c -> c.uppercase() } }} Wall")
                    .withItem {
                        tab(CreativeModeTabs.COLORED_BLOCKS)
                        tab(CreativeModeTabs.BUILDING_BLOCKS)
                        optionalTag(ItemTags.WALLS)
                        recipe { context, provider -> provider.wall(fullBlocks[dye]!!.asIngredient(), BUILDING_BLOCKS, context) }
                    }.register()
            }
        }
    }

    private fun registerPlaster() {
        DYES.associateWith { dye ->
            REGISTRATE
                .`object`("${dye}_plaster")
                .dyedBlock(dye, ARTS_AND_CRAFTS, ::createArtsAndCraftsPlaster)
                .initialProperties { BuiltInRegistries.BLOCK.get(ARTS_AND_CRAFTS.createId("cyan_plaster")) }
                .optionalTag(BlockTags.MINEABLE_WITH_PICKAXE)
                .blockstate { _, _ -> }
                .lang("${dye.translation} Plaster")
                .withItem {
                    tab(CreativeModeTabs.COLORED_BLOCKS)
                    tab(CreativeModeTabs.BUILDING_BLOCKS)
                }.register()
        }
    }

    private fun registerFlowerPots() {
        val flowerPots =
            DYES.associateWith { dye ->
                val dyeName = dye.serializedName
                REGISTRATE
                    .`object`("${dyeName}_flower_pot")
                    .dyedBlock(dye, ARTS_AND_CRAFTS) { props -> DyedFlowerPotBlock(dyeName, null, props) }
                    .initialProperties { BuiltInRegistries.BLOCK.get(ARTS_AND_CRAFTS.createId("yellow_flower_pot")) }
                    .blockstate { _, _ -> }
                    .lang("${dye.translation} Flower Pot")
                    .withItem {
                        tab(CreativeModeTabs.COLORED_BLOCKS)
                        tab(CreativeModeTabs.BUILDING_BLOCKS)
                    }.register()
            }

        DYES.forEach { dye ->
            val dyeName = dye.serializedName
            POTTED_VARIANTS.forEach { variant ->
                val plantId = ResourceLocation.parse(variant.plantId)
                REGISTRATE
                    .`object`("${dyeName}_${variant.suffix}")
                    .dyedBlock(dye, ARTS_AND_CRAFTS) { props -> DyedFlowerPotBlock(dyeName, plantId, props) }
                    .initialProperties { flowerPots[dye]!!.get() }
                    .blockstate { _, _ -> }
                    .register()
            }
        }
    }

    fun register() {
        registerBlockType("mud_brick", "mud_bricks", "cyan_mud_bricks")
        registerBlockType("terracotta_shingle", "terracotta_shingles", "cyan_terracotta_shingles")
        registerBlockType("soapstone", "soapstone", "cyan_soapstone")
        registerBlockType("polished_soapstone", "polished_soapstone", "cyan_polished_soapstone")
        registerBlockType("soapstone_brick", "soapstone_bricks", "cyan_soapstone_bricks")
        registerPlaster()
        registerFlowerPots()
        registerChalkBlocks()
        registerChalkDust()
        registerChalkSticks()
        registerPaintbrushes()
    }
}
